### ISSUE TITLE
Error with  *pyrdp-convert.py -f mp4*

### ISSUE THREAD

**Issue by yangyang5214** [GoSecure/pyrdp#425]
```
(venv) ➜  bin git:(master) ✗ python3 pyrdp-convert.py -f mp4 ~/rdp_replay_20221206_06-11-39_812_Lynn820947.pyrdp 
Traceback (most recent call last):
  File "pyrdp-convert.py", line 13, in <module>
    from pyrdp.convert.PCAPConverter import PCAPConverter
  File "/Users/beer/beer/pyrdp/pyrdp/convert/PCAPConverter.py", line 12, in <module>
    from scapy.layers.inet import TCP
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/layers/inet.py", line 22, in <module>
    from scapy.ansmachine import AnsweringMachine
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/ansmachine.py", line 20, in <module>
    from scapy.sendrecv import send, sniff
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 61, in <module>
    import scapy.route  # noqa: F401
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/route.py", line 218, in <module>
    conf.route = Route()
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/route.py", line 37, in __init__
    self.resync()
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/route.py", line 45, in resync
    from scapy.arch import read_routes
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/arch/__init__.py", line 124, in <module>
    from scapy.arch.bpf.supersocket import *  # noqa F403
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/arch/bpf/supersocket.py", line 27, in <module>
    from scapy.layers.l2 import Loopback
  File "/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/layers/l2.py", line 17, in <module>
    from scapy.ansmachine import AnsweringMachine
ImportError: cannot import name 'AnsweringMachine' from partially initialized module 'scapy.ansmachine' (most likely due to a circular import) (/Users/beer/beer/pyrdp/venv/lib/python3.8/site-packages/scapy/ansmachine.py)

```

I fixed by this,

![image](https://user-images.githubusercontent.com/23392325/206077659-e9fb4a62-aabc-451f-84f3-94726a091798.png)

**Comment by obilodeau** [comment]
Thanks for the report and the patch! :grin:

**Comment by obilodeau** [comment]
I am not able to reproduce the issue. Can you execute `pip freeze --local` in your virtual environment (venv) and report the dependency list here, please? I am also assuming you are running Windows. Is that correct?

**Comment by yangyang5214** [comment]
Sorry , I'm running in MacOS ,  and can work in docker env 👍

```
# When I see this sentence
This tool has been tested to work on Python 3.6 on Linux (Ubuntu 18.04, 20.04), Raspberry Pi and Windows (see section [Installing on Windows](https://github.com/GoSecure/pyrdp#installing-on-windows)). It has not been tested on macOS.
```
